//auth
export const USER_LOADING = "USER_LOADING ";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR ";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS ";
export const LOGIN_FAIL = "LOGIN_FAIL ";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS ";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//user
export const SEND_INVITE = "SEND_INVITE";
export const CANCEL_FRIEND_REQUEST = "CANCEL_FRIEND_REQUEST";
export const REMOVE_INVITE = "REMOVE_INVITE";
export const ACCEPT_INVITE = "ACCEPT_INVITE";
