export const GET_CHAT = "GET_CHAT";
export const CHAT_LOADING = "CHAT_LOADING";
export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const CLOSE_CHAT = "CLOSE_CHAT";
export const REMOVE_UNREAD_MESSAGES = "REMOVE_UNREAD_MESSAGES";
